# -*- coding: utf-8 -*-
"""Model Building

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AoUEXZIcVLK8WOXx_5OD_uDBxiojclpf
"""

#import keras libraries
import numpy as np
import tensorflow
from tensorflow.keras.models import Squential
from tensorflow.keras import layers
from tensorflow.keras.layers import Dense,Flatten
from tensorflow.keras.layers import Conv2D,MaxPooling2D,Dropout
from keras.preprocessing.image ImageDataGenerator
#Intialize CNN model
model=Sequential()
#Add Convolution Layer
model.add(Conv2D(32,3,3,input_shape=(64,64,3),activation='relu'))
#Add Pooling Layer
model.add(MaxPooling2D(pool_size=(2,2)))
#Add flatten layer
model.add(Flatten())
#Adding Dense layer
model.add(Dense(300,activation='relu'))
model.add(Dense(150,activation='relu'))
#Configure the Learning process
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['ac
curacy'])
#Train the model
model.fit_generator(x_train,samples_per_epoch =
8000,epochs=25,validation_data=x_test,nb_val_samples=2000)
#Save the model
model.save('nutrition.h5')
#Test the model
import numpy as np 
from tensorflow.keras.models import load_model 
from tensorflow.keras.preprocessing import image
model=load_model('nutrition.h5')
img=image.load_img(r'/content/drive/MyDrive/nutrition/Watermelon/ 
10386503264_e05387e1f7_m.jpg')
img
x=image.img_to_array(img) x=np.expand_dims(x,axis=0)
pred_prob=model.predict(x)
class_name=["Apple,Banana,Orange,Pineapple,Watermelon"]
pred_id=pred_prob.argmax(axis=1)[0] pred_id